/**
 * Export utilities for CSV and PDF downloads.
 * No external libraries required.
 */

// ─── CSV Export ───────────────────────────────────────────────────────────────

/**
 * Converts an array of flat objects to a CSV string and triggers a browser download.
 * Supports multi-section reports by passing an array of { title, rows } blocks.
 */
export interface CSVSection {
  title: string;
  rows: Record<string, string | number>[];
}

export function exportToCSV(filename: string, sections: CSVSection[]): void {
  const lines: string[] = [];

  for (const section of sections) {
    if (section.rows.length === 0) continue;

    lines.push(`"${section.title}"`);
    const headers = Object.keys(section.rows[0]);
    lines.push(headers.map((h) => `"${h}"`).join(","));

    for (const row of section.rows) {
      const values = headers.map((h) => {
        const val = row[h] ?? "";
        return `"${String(val).replace(/"/g, '""')}"`;
      });
      lines.push(values.join(","));
    }

    lines.push(""); // blank row between sections
  }

  const csv = lines.join("\r\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

// ─── PDF Export (print-based, no libraries) ───────────────────────────────────

export interface PDFSection {
  title: string;
  rows: Record<string, string | number>[];
}

export function exportToPDF(
  reportTitle: string,
  sections: PDFSection[],
  generatedAt?: string,
): void {
  const date = generatedAt || new Date().toLocaleString();

  let tableHTML = "";
  for (const section of sections) {
    if (section.rows.length === 0) continue;
    const headers = Object.keys(section.rows[0]);

    tableHTML += `
      <h2 style="margin-top:28px;margin-bottom:8px;font-size:14px;color:#1e3a5f;font-family:sans-serif;">${section.title}</h2>
      <table>
        <thead>
          <tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr>
        </thead>
        <tbody>
          ${section.rows
            .map(
              (row) =>
                `<tr>${headers
                  .map((h) => `<td>${row[h] ?? "-"}</td>`)
                  .join("")}</tr>`,
            )
            .join("")}
        </tbody>
      </table>`;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${reportTitle}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: sans-serif; color: #1a1a2e; padding: 32px; font-size: 13px; }
    header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #2563eb; }
    header h1 { font-size: 20px; font-weight: 900; color: #1e3a5f; }
    header span { font-size: 11px; color: #999; }
    .badge { font-size: 10px; background: #eff6ff; color: #2563eb; padding: 4px 10px; border-radius: 99px; font-weight: 700; margin-top: 4px; display: inline-block; }
    h2 { font-size: 13px; font-weight: 800; color: #1e3a5f; text-transform: uppercase; letter-spacing: 0.1em; margin-top: 28px; margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    th { background: #eff6ff; color: #2563eb; text-align: left; padding: 8px 12px; font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 2px solid #bfdbfe; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; font-size: 12px; color: #374151; }
    tr:nth-child(even) td { background: #f8fafc; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    @media print { body { padding: 16px; } @page { margin: 1.5cm; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>${reportTitle}</h1>
      <span class="badge">ASTU Smart Complaint &amp; Issue Tracking System</span>
    </div>
    <span>Generated: ${date}</span>
  </header>
  ${tableHTML}
  <footer>This report was automatically generated by the ASTU Complaint Management System &bull; Confidential</footer>
</body>
</html>`;

  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "none";
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(html);
  doc.close();

  // Wait for content to render then print
  setTimeout(() => {
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 1000);
  }, 400);
}

// ─── Date helper ─────────────────────────────────────────────────────────────

export function todayString(): string {
  return new Date().toISOString().slice(0, 10);
}
